name: CI/CD for backend

on:
  push:
    branches:
      - test-cicd-vm2-with-sec

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: .github/workflows/sitst-client.ovpn
        username: ${{ secrets.OVPN_USERNAME }}
        password: ${{ secrets.OVPN_PASSWORD }}
      
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: SSH into Azure VM and pull new code
      run: |
        ssh -o StrictHostKeyChecking=no sysadmin@10.4.85.24 "cd /home/sysadmin/backend-js && git pull"

    - name: Show Docker container status
      run: |
        ssh -o StrictHostKeyChecking=no sysadmin@10.4.85.24 "docker ps -a"

    # - name: Stop and remove existing containers
    #   run: |
    #     ssh -o StrictHostKeyChecking=no sysadmin@10.4.85.24 "cd /home/sysadmin/proxy && docker-compose stop backend-container"
    #     ssh -o StrictHostKeyChecking=no sysadmin@10.4.85.24 "cd /home/sysadmin/proxy && docker-compose rm -f backend-container"

    # - name: Rebuild Docker containers
    #   run: |
    #     ssh -o StrictHostKeyChecking=no sysadmin@10.4.85.24 "cd /home/sysadmin/proxy && docker-compose up -d --build backend-container"

    # - name: Show Docker container status
    #   run: |
    #     ssh -o StrictHostKeyChecking=no sysadmin@10.4.85.24 "docker ps -a"

    # Install Docker
    - name: Install Docker
      run: |
        sudo apt update
        sudo apt remove -y containerd.io
        sudo apt install -y docker.io

    # Install Trivy
    - name: Install Trivy
      run: |
        sudo apt update
        sudo apt install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt update
        sudo apt install -y trivy


    - name: Show Docker images
      run: |
        ssh -o StrictHostKeyChecking=no sysadmin@10.4.85.24 "docker image ls"

    # Scan Docker image with Trivy
    - name: Trivy Scan
      run: |
        trivy image --quiet backend-image

    # Install OWASP ZAP scan
    - name: Install OWASP ZAP
      run: |
        sudo apt update
        sudo apt install -y owasp-zap

    # Run OWASP ZAP scan
    - name: OWASP ZAP Scan
      run: |
        zap-baseline.py -t https://capstone23.sit.kmutt.ac.th/nw4/ -r report.html
